### ISSUE TITLE
Issue to trigger new release

### ISSUE THREAD

**Issue by ablaom** [JuliaAI/MLJModelInterface.jl#60]
@JuliaRegistrator register

**Comment by ablaom** [comment]
@JuliaRegistrator register

**Comment by ablaom** [comment]
@JuliaRegistrator register

**Comment by ablaom** [comment]
@JuliaRegistrator register

**Comment by ablaom** [comment]
@JuliaRegistrator register

**Comment by ablaom** [comment]
@JuliaRegistrator register

**Comment by ablaom** [comment]
@JuliaRegistrator register

**Comment by ablaom** [comment]
@JuliaRegistrator register

**Comment by ablaom** [comment]
@JuliaRegistrator register

**Comment by ablaom** [comment]
@JuliaRegistrator

**Comment by ablaom** [comment]
@JuliaRegistrator register

**Comment by ablaom** [comment]
@JuliaRegistrator register

**Comment by ablaom** [comment]
@JuliaRegistrator register

release notes:

- [x] Add support for iterative models (#91, https://github.com/alan-turing-institute/MLJ.jl/issues/139)

**Comment by ablaom** [comment]
@JuliaRegistrator register

release notes:

- Extend compatibility requirement for StatisticalTraits to include v1.0.

**Comment by ablaom** [comment]
@JuliaRegistrator register

release notes:

- [x] Make `==` for MLJType objects property-based instead of field-based (#97)

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

release notes:

- [x] Add fallbacks for new traits defined at https://github.com/JuliaAI/StatisticalTraits.jl/pull/18 (#109)

**Comment by ablaom** [comment]
@JuliaRegistrator register branch = master

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

release notes:

- [x] (**enhancement**) Add support for outlier detection (#113)

**Comment by ablaom** [comment]
cc @davnn

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

release notes:

- [x] (**bug fix**) Fix unexpected behaviour of `==` for MLJTypes objects with "strap-on" properties (#115)

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

**Comment by ablaom** [comment]
cc @davnn

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

release notes: 

- Tweak `fit` and trait fallbacks for `Annotator` models (#121)  @davnn

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

release notes:

- Bump the compatibility requirements of `ScientificTypesBase` to `^3`, making necessary adjustments (#126) @OkonSamuel

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

Release notes:

- (**ehancement**) Add utility `doc_header` for generating a standard header for MLJ model document strings 
- (**future proofing**) Ensure `metadata_model` utility does not override fallback behaviour of model traits 
- (**enhancement**) Add `human_name` as a model trait with fallback provided by StatisticalTraits.jl  (eg, "XGBoostRegressor" -> "XG boost regressor") 
- (**enhancement**) Add `human_name` and `supports_class_weights` to list of traits that can be declared using `metadata_model` 
- Change `docstring` trait fallback to be the regular type doc-string if it exists, and to otherwise be an auto-generated string that improves the previous fallback.

Details are to be found in #139 and #140.

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

Release notes:

- (**enhancement**) Add support for feature importances (#148) @OkonSamuel

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

Release notes:

- (**enhancement**) Add `reporting_operations`, from StatisticalTraits.jl,  to the list of model traits (#158)

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

Release notes:

- Add a new model method `report(::Model, report_given_method)` for combining the reports generated by a model's `fit` method, with reports generated by operations, such as `predict`. Here `report_given_method` is a dictionary of reports, keyed on methods as symbols (`:fit`, `:predict`, `:transform`, and so forth) (#160; in support of https://github.com/JuliaAI/MLJBase.jl/pull/841)

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

Release notes:

- Add `ProbabilisticSet <: Supervised` model type (#167) 
- Add `augment` keyword option to `doc_header` (#168)

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

Release notes:

- Add `flat_params` method for converting a nested model to a named tuple (#177) @pebeto

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

**Comment by ablaom** [comment]
Huh?? Registration PR not triggered for some reason. Registered at JuliaHub instead. Here's the PR: 

https://github.com/JuliaRegistries/General/pull/89710

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

Release notes:

- Fix a bug with `@mlj_model` macro (#174) @MilesCranmer

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

- Add the new trait `target_in_fit` from StatisticalTraits.jl (#204)

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

Release notes:

- Add `tags` trait (#219)

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master
